# Generated by Django 4.1 on 2022-09-02 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_super', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='email_empresa',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre_empresa',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='telefono_empresa',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='email_viajante',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre_viajante',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='telefono_viajante',
        ),
    ]
